name: SimpleUtils
version: '1.0.1-X'
main: org.crit.simpleUtils.SimpleUtils
api-version: '1.21'
description: 'A utility plugin meant to eliminate the need of multiple plugins, Designed to have the basics features servers may need.'
authors:
  - 'Your mom'
  - 'ft. Ccr1tt'

commands:
  dupe:
    description: Dupes the item in your hand!
    aliases:
      - dp
      - dup
      - upe
    permission-message: You lack the permission to run this!
    usage: /<command> <optional amount>
    permission: dupe_vanish_SIMPLEUTIL

  fly:
    description: Lets you fly around the world! Use it again to stop flying!
    permission: flight_vanish_SIMPLEUTIL
    usage: /<command> (TOGGLE)

  dupeblacklist:
    description: Adds a player to the dupe blacklist!
    permission: dupe_blacklistUSE_vanish_SIMPLEUTIL
    usage: /<command> <Player> (TOGGLE THEIR STATUS)
    permission-message: You lack the permissions to run this!

  vanish:
    description: Vanishes you or other players
    permission: vanish_SIMPLEUTIL
    usage: /<command> <Player> (toggle)
    permission-message: You suck ash!

  enchant:
    description: Enchants the item in your hand!
    permission: enchant_vanish_SIMPLEUTIL
    usage: /<command> <enchant> <level>
    permission-message: Enchants stuff

  simpleutils:
    description: Information on the server & the plugin!
    usage: /<command> <req>
    permission-message: You cant do this brochanco



